import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className='h-screen flex'>
       <h1 className="text-3xl m-auto text-red-500 font-bold underline">
       Comming soon...
    </h1>
       </div>
    </>
  )
}
